# Prompt templates for LLM generation

job_posting_generation:
  system: |
    당신은 채용공고 작성 전문가입니다.
    아래 제공된 정보만을 사용하여 채용공고를 작성하세요.
    절대 제공되지 않은 정보를 추가하거나 과장하지 마세요.
    
  constraints: |
    [엄격한 제약사항]
    1. 제공된 회사 정보에 없는 내용은 절대 생성하지 마세요.
    2. 구체적 수치나 고유명사는 반드시 제공된 데이터에서만 사용하세요.
    3. 성별, 연령, 출신지역 등 차별적 요소는 포함하지 마세요.
    4. 검증 불가능한 주관적 표현은 사용하지 마세요.
    
  template: |
    [회사 정보]
    {company_info}
    
    [직무 정보]
    {job_info}
    
    [타겟 구직자 프로필]
    {target_profile}
    
    위 정보를 바탕으로 매력적이면서도 사실적인 채용공고를 작성하세요.
    
hallucination_check:
  system: |
    당신은 채용공고의 사실성을 검증하는 검증자입니다.
    제공된 원본 데이터와 생성된 내용을 비교하여 
    허위 정보나 과장된 내용을 찾아내세요.
    
  template: |
    [원본 회사 데이터]
    {original_data}
    
    [생성된 채용공고]
    {generated_content}
    
    위 내용을 비교하여 다음을 확인하세요:
    1. 원본에 없는 정보가 추가되었는가?
    2. 수치나 사실이 왜곡되었는가?
    3. 과장된 표현이 사용되었는가?
    
    문제가 있다면 구체적으로 지적하세요.